-- AlterTable
ALTER TABLE `Landmark` ADD COLUMN `baths` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `bedrooms` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `beds` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `maxGuests` INTEGER NOT NULL DEFAULT 1;
